{
  try {
    super.runTest();
  }
 catch (  AssertionFailedError e) {
    log.severe(EMPTY_LINE);
    log.log(Level.SEVERE,"ASSERTION FAILED: " + e,e);
    throw e;
  }
catch (  Throwable e) {
    log.severe(EMPTY_LINE);
    log.log(Level.SEVERE,"EXCEPTION: " + e,e);
    throw e;
  }
 finally {
    Clock.reset();
  }
}
